const Class = require("../models/Class");
const Schedule = require("../models/Schedule");
const Teacher = require("../models/Teacher");
const Student = require("../models/Student");

// 1. Create a Class (Admin)
exports.createClass = async (req, res) => {
  try {
    // classId will be auto-generated by Model if not provided
    // If classId is provided in req.body, it will be used. Otherwise, MongoDB will generate _id.
    // The instruction implies removing manual generation and allowing the model to handle it,
    // or explicitly passing req.body.classId if it exists.
    // Using spread syntax for req.body and then overriding/adding specific fields is a common pattern.
    const newClass = await Class.create({
      ...req.body, // Spreads all properties from req.body
      status: "Pending", // Explicitly set or override status
    });

    res.status(201).json(newClass);
  } catch (err) {
    res.status(400).json({ message: err.message });
  }
};

// 2. Get All Classes (with filters)
exports.getAllClasses = async (req, res) => {
  try {
    const { teacherId, status, keyword } = req.query;
    const filter = {};

    if (teacherId) filter.teacherId = teacherId;
    if (status) filter.status = status;
    if (keyword) {
        filter.className = { $regex: keyword, $options: 'i' };
    }

    const classes = await Class.find(filter)
      .populate("teacherId", "fullName email phone")
      .sort("-createdAt");

    res.json(classes);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

// 3. Get Class Detail
exports.getClassById = async (req, res) => {
  try {
    const classItem = await Class.findById(req.params.id)
        .populate("teacherId", "fullName email"); // Add students populate later via Enrollment

    if (!classItem) {
      return res.status(404).json({ message: "Lớp học không tồn tại" });
    }

    res.json(classItem);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

// 4. Update Class
exports.updateClass = async (req, res) => {
  try {
    const classItem = await Class.findByIdAndUpdate(req.params.id, req.body, {
      new: true,
      runValidators: true
    });

    if (!classItem) {
      return res.status(404).json({ message: "Lớp học không tồn tại" });
    }

    res.json(classItem);
  } catch (err) {
    res.status(400).json({ message: err.message });
  }
};

// 5. Delete Class
exports.deleteClass = async (req, res) => {
  try {
    const classItem = await Class.findByIdAndDelete(req.params.id);
    if (!classItem) {
      return res.status(404).json({ message: "Lớp học không tồn tại" });
    }
    
    // TODO: Handle related enrollments (prevent delete if students exist?)
    
    res.json({ message: "Đã xóa lớp học" });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};
